owner: petebachant
name: test-1
title: Test 1
description: This is a test.
git_repo_url: https://github.com/petebachant/test-1

environments:
  main:
    kind: uv
    path: pyproject.toml

  tex:
    kind: docker
    image: texlive/texlive:latest-full
    description: TeXlive via Docker.
pipeline:
  stages:
    analyze-penguins:
      kind: jupyter-notebook
      notebook_path: notebooks/penguins.ipynb
      environment: main
      inputs:
        - data/raw/penguins.csv
      outputs:
        - path: figures
          storage: git
        - path: tables
          storage: git

    build-paper:
      name:
      kind: latex
      environment: tex
      wdir:
      inputs: []
      outputs: []
      always_run: false
      iterate_over:
      description:
      target_path: paper/main.tex
      latexmkrc_path:
      verbose: false
      force: false
      synctex: true
notebooks:
  - path: notebooks/penguins.ipynb
    title: Penguins analysis
    description: >
      A modified version of Saswat Seth's penguins analysis notebook.
    imported_from:
      url: 
        https://www.kaggle.com/code/saswatsethda/penguins-data-analysis-and-modeling
    license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0

datasets:
  - path: data/raw/penguins.csv
    title: Palmer's penguins
    imported_from:
      doi: 10.5281/zenodo.3960218
    license: CC0-1.0
    notes: >
      CSV from
      https://github.com/INRIA/scikit-learn-mooc/blob/main/datasets/penguins.csv
derived_from:
  project: calkit/example-analytics
  git_repo_url: https://github.com/calkit/example-analytics
  git_rev: 36bc3038c7638d96770e3eddcb44f930e2bec4bb
publications:
  - path: paper/main.pdf
    title: The paper
    description:
    kind:
    stage: build-paper
    overleaf:
      project_id: 54b68eff0ee71ad2767b704a
      wdir: paper
      sync_paths: []
      push_paths: []
      last_sync_commit:
