owner: petebachant
name: test-1
title: Test 1
description: ""
git_repo_url: https://github.com/petebachant/test-1

storage:
  dvc:
    kind: calkit-cloud
  git-lfs:
    kind: hugging-face
    repo_url: petebachant/test-1-lfs

environments:
  tex:
    kind: docker
    image: texlive/texlive:latest-full
  py:
    kind: uv
    path: .calkit/envs/py/pyproject.toml
  cluster:
    kind: slurm
    partition: gpu
    host: sup.lol.edu
  j1:
    kind: julia
    path: Project.toml
    julia: "1.12"
  jupydocker:
    kind: docker
    image: quay.io/jupyter/scipy-notebook:2025-12-31
  conda-polars:
    path: environment.yml
    kind: conda

pipeline:
  stages:
    notebook:
      kind: jupyter-notebook
      notebook_path: notebook.ipynb
      environment: py
      outputs:
        - figures/test.png
    build-paper:
      kind: latex
      target_path: paper/main.tex
      environment: tex
      inputs:
        - paper/figures
    build-paper2:
      kind: latex
      target_path: paper2/main.tex
      environment: tex
      inputs:
        - paper2/thing.txt
        - paper2/figures
    build-report:
      kind: latex
      target_path: report/main.tex
      environment: tex
      inputs:
        - report/references.bib
        - report/figures
    notebook-julia:
      kind: jupyter-notebook
      notebook_path: notebook-julia.ipynb
      html_storage: git
      executed_ipynb_storage: git
      environment: j1
      outputs:
        - figures/sine.png
    notebooks-conda-polars:
      kind: jupyter-notebook
      notebook_path: notebooks/conda-polars.ipynb
      html_storage: git
      executed_ipynb_storage: git
      environment: conda-polars
      outputs:
        - notebooks/data.avro
        - notebooks/data.parquet
    notebooks-other:
      kind: jupyter-notebook
      notebook_path: notebooks/other.ipynb
      html_storage: git
      executed_ipynb_storage: git
      environment: py
      outputs:
        - path: results/sup.json
          storage: git

publications:
  - path: paper/main.pdf
    title: A paper about things
    description:
    kind: journal-article
    stage: build-paper
  - path: paper2/main.pdf
    title: A paper about things
    description:
    kind: report
    stage: build-paper2
  - path: report/main.pdf
    title: A Simple Workflow for Processing and Visualizing Experimental
      Data
    description:
    kind: report
    stage: build-report

showcase:
  - publication: paper/main.pdf

questions:
  - What's up?
  - This is another question?
  - Will this update my full name?
  - Can I still add a question?

notebooks:
  - path: notebook.ipynb
    environment: py
  - path: notebooks/conda-polars.ipynb
    environment: conda-polars
  - path: notebooks/other.ipynb
    environment: py

overleaf_sync:
  paper2:
    url: https://www.overleaf.com/project/54b68eff0ee71ad2767b704a
  report:
    url: https://www.overleaf.com/project/699f2a0fb20a38960a52bc26

figures:
  - path: figures/ups2.jpg
    imported_from:
      url: something.net
  - path: figures/sick/portland-ups.jpeg
    imported_from:
      url: https://google.net
  - path: figures/test.png
    imported_from:
      url: https://something.net
  - path: paper/figures/000_000000000250000.png
    imported_from:
      url: cool.net
  - path: paper2/figures/000_000000000250000.png
    imported_from:
      url: super.cool.net
  - path: report/figures/processed_derivative.png
    imported_from:
      url: yep.com
  - path: paper2/figures/cool.pdf
    imported_from:
      url: sock.net
  - path: report/figures/processed_smooth.png
    imported_from:
      url: cool.yo
  - path: report/figures/processed_timeseries.png
    imported_from:
      url: example.sweet
  - path: report/figures/raw-data-spectra.png
    imported_from:
      url: ggg
  - path: report/figures/raw_correlation.png
    imported_from:
      url: gggggg
  - path: report/figures/raw_distributions.png
    imported_from:
      url: ggg
  - path: report/figures/raw_scatter3d.png
    imported_from:
      url: fffff
  - path: report/figures/raw_spectrogram.png
    imported_from:
      url: fffffff
  - path: report/figures/raw_timeseries.png
    imported_from:
      url: ffff
